package com.dresos.nexus.moderation

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Contract test for the shipped `moderation/profanity_en.txt` asset (generated by
 * `scripts/gen-profanity-list.py` from the vendored dsojevic corpus).
 *
 * The invariants here are what stop a future regeneration from silently shipping a **dead entry**: a
 * multi-word, punctuated, or digit-bearing term the whole-token [LexicalTextFilter] could never match.
 * The file is read directly from disk (module-dir cwd, like [SentencePieceTokenizerTest]) and parsed
 * with the same rules as [WordList.load] — a fast, deterministic JVM test with no Robolectric host.
 */
class WordListTest {
    private val terms: List<String> by lazy {
        // Gradle runs unit tests with the module dir as the working dir.
        val file =
            listOf(
                "src/main/assets/moderation/profanity_en.txt",
                "app/src/main/assets/moderation/profanity_en.txt",
            ).map(::File).firstOrNull { it.exists() }
                ?: error("profanity_en.txt not found (cwd=${File(".").absolutePath})")
        // Mirror WordList.load: trim, drop blank lines and '#' comments.
        file
            .readLines()
            .map(String::trim)
            .filter { it.isNotEmpty() && !it.startsWith("#") }
    }

    @Test
    fun listLoadsAndIsNonEmpty() {
        assertTrue("the bundled profanity_en.txt should parse to a non-empty list", terms.isNotEmpty())
    }

    @Test
    fun everyTermIsASingleLowercaseToken() {
        // A pure [a-z]+ literal is invariant under normalize() and cannot be split on [^a-z]+, so it is
        // exactly one matchable token. Any space/hyphen/apostrophe/digit/uppercase = a dead entry.
        terms.forEach { term ->
            assertTrue("dead or non-[a-z] term shipped: '$term'", term.matches(TOKEN))
        }
    }

    @Test
    fun noTermIsDangerouslyShort() {
        terms.forEach { term ->
            assertTrue("term shorter than $MIN_LEN chars over-blocks: '$term'", term.length >= MIN_LEN)
        }
    }

    @Test
    fun noDuplicates() {
        assertEquals("the list should not contain duplicates", terms.size, terms.toHashSet().size)
    }

    @Test
    fun listIsSorted() {
        // Guards the generator's deterministic sort so regenerations produce clean, reviewable diffs.
        assertEquals(terms.sorted(), terms)
    }

    @Test
    fun sentinelProfanityIsPresent() {
        assertTrue(terms.containsAll(listOf("fuck", "shit", "cunt", "asshole", "bitch")))
    }

    @Test
    fun neutralIdentityTermsAreExcluded() {
        // The lgbtq tag is dropped: a context-free whole-token block can't tell self-description from a
        // slur, so genuine anti-LGBTQ slurs are left to the ML identity_attack pass.
        listOf("gay", "lesbian", "queer", "trans", "transgender", "bisexual", "homosexual").forEach {
            assertFalse("neutral identity term must not be blocked lexically: '$it'", it in terms)
        }
    }

    @Test
    fun commonInnocentWordsAreExcluded() {
        listOf("sex", "nude", "nudity", "topless", "collared").forEach {
            assertFalse("common innocent word must not be blocked lexically: '$it'", it in terms)
        }
    }

    @Test
    fun realCorpusMatchesFilterAndStaysScunthorpeSafe() {
        val filter = LexicalTextFilter(terms)
        assertTrue(filter.check("what the fuck").flagged)
        assertFalse(filter.check("classic assistant in Scunthorpe").flagged) // "cunt" is a substring only
        assertFalse(filter.check("hello there, friend").flagged)
    }

    private companion object {
        const val MIN_LEN = 3
        val TOKEN = Regex("^[a-z]+$")
    }
}
